identifier: com.snow.dislikes-skipper
name: Dislikes Skipper
description: Skip songs which have been marked as "suggest less" aka disliked
author: Snow
repo: https://github.com/kibbewater/dislikes-skipper
entry:
    'plugin.js':
        type: main
